// AUTH TYPES

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";
export const RESET_PASSWORD_CONFIRM_FAIL = "RESET_PASSWORD_CONFIRM_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const POST_LIST_LOADING = "POST_LIST_LOADING";
export const POST_LIST_LOADED_SUCCESS = "POST_LIST_LOADED_SUCCESS";
export const POST_LIST_LOADED_FAIL = "POST_LIST_LOADED_FAIL";
export const POST_DETAIL_LOADED_SUCCESS = "POST_DETAIL_LOADED_SUCCESS";
export const POST_DETAIL_LOADED_FAIL = "POST_DETAIL_LOADED_FAIL";
export const USER_LOADING = "USER_LOADING";
export const MY_DATA_LOADING = "MY_DATA_LOADING";
export const MY_DATA_LOADED_SUCCESS = "MY_DATA_LOADED_SUCCESS";
export const MY_DATA_LOADED_FAIL = "MY_DATA_LOADED_FAIL";
export const USER_PROFILE_DATA_LOADING = "USER_PROFILE_DATA_LOADING";
export const USER_PROFILE_DATA_LOADED_SUCCESS =
  "USER_PROFILE_DATA_LOADED_SUCCESS";
export const USER_PROFILE_DATA_LOADED_FAIL = "USER_PROFILE_DATA_LOADED_FAIL";
export const POST_DETAIL_LOADING = "POST_DETAIL_LOADING";
export const POST_SUBMITING = "POST_SUBMITING";
export const POST_SUBMITED_SUCCESS = "POST_SUBMITED_SUCCESS";
export const POST_SUBMITED_FAIL = "POST_SUBMITED_FAIL";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_LOADED_SUCCESS = "COMMENTS_LOADED_SUCCESS";
export const COMMENTS_LOADED_FAIL = "COMMENTS_LOADED_FAIL";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADED_SUCCESS = "PRODUCTS_LOADED_SUCCESS";
export const PRODUCTS_LOADED_FAIL = "PRODUCTS_LOADED_FAIL";
export const POST_LIKE_LOADING = "POST_LIKE_LOADING";
export const POST_LIKEING_SUCCESS = "POST_LIKEING_SUCCESS";
export const POST_LIKEING_FAIL = "POST_LIKEING_FAIL";
export const UNIVERSITY_LIST_LOADING = "UNIVERSITY_LIST_LOADING";
export const UNIVERSITY_LIST_LOADED_S = "UNIVERSITY_LIST_LOADED_S";
export const UNIVERSITY_LIST_LOADED_F = "UNIVERSITY_LIST_LOADED_F";
export const BOOKMARK_GROUP_DELETE_LOADING = "BOOKMARK_GROUP_DELETE_LOADING";
export const BOOKMARK_GROUP_DELETE_SUCCESS = "BOOKMARK_GROUP_DELETE_SUCCESS";
export const BOOKMARK_GROUP_DELETE_FAIL = "BOOKMARK_GROUP_DELETE_FAIL";

// SHOP TYPES

export const RESTAURANT_LOADING = "RESTAURANT_LOADING";
export const RESTAURANT_LOADED_SUCCESS = "RESTAURANT_LOADED_SUCCESS";
export const RESTAURANT_LOADED_FAIL = "RESTAURANT_LOADED_FAIL";
export const RESTAURANT_ITEM_LOADING = "RESTAURANT_ITEM_LOADING";
export const RESTAURANT_ITEM_LOADED_SUCCESS = "RESTAURANT_ITEM_LOADED_SUCCESS";
export const RESTAURANT_ITEM_LOADED_FAIL = "RESTAURANT_ITEM_LOADED_FAIL";
export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const RESTAURANT_DETAIL_LOADING = "RESTAURANT_DETAIL_LOADING";
export const RESTAURANT_DETAIL_LOADED_SUCCESS =
  "RESTAURANT_DETAIL_LOADED_SUCCESS";
export const RESTAURANT_DETAIL_LOADED_FAIL = "RESTAURANT_DETAIL_LOADED_FAIL";
export const REFRESH_CART_LOADING = "REFRESH_CART_LOADING";
export const REFRESH_CART_SUCCESS = "REFRESH_CART_SUCCESS";
export const REFRESH_CART_FAIL = "REFRESH_CART_FAIL";
